(define (problem han1)
	(:domain hanoi)
	(:objects k1 k2 k3 k4 k5 - disk)
	(:init
		(lt k1 k2) (lt k1 k3) (lt k1 k4) (lt k1 k5)
		(lt k2 k3) (lt k2 k4) (lt k2 k5)
		(lt k3 k4) (lt k3 k5)
		(lt k4 k5)
		(on-rod k1 x)
		(on-rod k2 x)
		(on-rod k3 x)
		(on-rod k4 x)
		(on-rod k5 x)
	)
	(:goal (and
		(on-rod k1 z)
		(on-rod k2 z)
		(on-rod k3 z)
		(on-rod k4 z)
		(on-rod k5 z)	
		)
	)
)