(define (problem mwbe1)
	(:domain merry-w-bag-end)
	(:objects zie cze pom roz nie - color blk1 blk2 blk3 blk4 blk5 blk6 blk7 blk8 - block)
	(:init
		(man F)
		(way zie C E) (way zie E C) (way zie D F) (way zie F D)
		(way cze A C) (way cze C A) (way cze E H) (way cze H E)
		(way pom A B) (way pom B D)
		(way roz F G)
		(way nie E F) (way nie F E) (way nie F I) (way nie I F) (way nie H I) (way nie I H)
		(lie-one zie A) (lie-one zie D) (lie-one zie E) (lie-one zie H)
		(lie-one cze D) (lie-one cze H)
		(lie-one pom C) (lie-one pom I)
		(lie-one roz B)
		(lie-one nie C) (lie-one nie E) (lie-one nie I) (lie-two nie F)
		(on blk5 a1) (on blk4 a2) (on blk1 a3)
		(on blk8 b1) (empty b2) (on blk3 b3)
		(on blk7 c1) (on blk2 c2) (on blk6 c3)
		(connect a1 a2) (connect a1 b1)
		(connect a2 a1) (connect a2 b2) (connect a2 a3)
		(connect a3 a2) (connect a3 b3)
		(connect b1 a1) (connect b1 b2) (connect b1 c1)
		(connect b2 a2) (connect b2 b1) (connect b2 b3) (connect b2 c2)
		(connect b3 a3) (connect b3 b2) (connect b3 c3)
		(connect c1 b1) (connect c1 c2)
		(connect c2 c1) (connect c2 b2) (connect c2 c3)
		(connect c3 c2) (connect c3 b3)
	)
	(:goal
		(and
			(man G)
			(on blk1 a1) (on blk2 a2) (on blk3 a3)
			(on blk4 b1) (on blk5 b2) (on blk6 b3)
			(on blk7 c1) (on blk8 c2) (empty c3)
		)
	)
)